// Fastify plugin autogenerated by fastify-openapi-glue
import openapiGlue from "../../lib/templates/index.js";
import { Service } from "./service.js";
import { Security } from "./security.js";
const localFile = (fileName) => new URL(fileName, import.meta.url).pathname;

const pluginOptions = {
	specification: localFile("./openApi.json"),
	service: new Service(),
	securityHandlers: new Security(),
};

export default async function (fastify, opts) {
	fastify.register(openapiGlue, pluginOptions);
}

export const options = {
	ajv: {
		customOptions: {
			strict: false,
		},
	},
};
