export default (data) => `// Fastify plugin autogenerated by fastify-openapi-glue

import fastifyPlugin from "fastify-plugin";
import { Service } from "./${data.serviceFile}";
import { Security } from "./${data.securityFile}";

function notImplemented(operationId) {
	return async () => {
		throw new Error(\`Operation \${operationId} not implemented\`);
	};
}

export default fastifyPlugin(
	async function (fastify, opts) {
		const service = new Service();
		const security = new Security();
${data.config.routes
	.map(
		(item) =>
			`		fastify.route({
			method: "${item.method}",
			url: "${item.url}",
			schema: ${optimizeSchema(item.schema)},
			${
				item.config
					? `config: ${item.config},
			`
					: ""
			}handler: service["${item.operationId}"].bind(Service)
		});
`,
	)
	.join("\n")}
}, { fastify: '^4.x' })

export const options = {
	ajv: {
		customOptions: {
			strict: false,
		},
	},
};
`;

function optimizeSchema(schema, indent = 3) {
	const prefix = `${"\t".repeat(indent)}`;
	const schemaKeys = ["body", "query", "querystring", "params", "reponse"];
	const newSchema = {};
	for (const key of schemaKeys) {
		if (schema[key] !== undefined) {
			newSchema[key] = schema[key];
		}
	}
	return JSON.stringify(newSchema, null, "\t");
}
