export default (projectName, instructions) => `# ${projectName}

This directory contains a fastify plugin that was autogenerated using 
[fastify-openapi-glue](https://github.com/seriousme/fastify-openapi-glue) and 
the OpenApi specifation in [openApi.json](openApi.json)
${instructions}
`;
