// Fastify plugin autogenerated by fastify-openapi-glue
import openapiGlue from "fastify-openapi-glue";
import { dirname } from "fastify-openapi-glue/lib/dirname-esm.js";
const dir = dirname(import.meta);

const options = {
  specification: `${dir}/openApi.json`,
  service: `${dir}/service.js`,
  securityHandlers: `${dir}/security.js`
};

export default async function (fastify, opts) {
  fastify.register(openapiGlue, options);
};
