// Fastify plugin autogenerated by fastify-openapi-glue
import openapiGlue from "fastify-openapi-glue";
import { Service } from "./service.js";
import { Security } from "./security.js";
const localFile = ( fileName ) => (new URL(fileName,import.meta.url)).pathname

const options = {
  specification: localFile('./openApi.json'),
  service: new Service(),
  securityHandlers: new Security(),
};

export default async function (fastify, opts) {
  fastify.register(openapiGlue, options);
};
