export default data => `// Fastify plugin autogenerated by fastify-openapi-glue
import openapiGlue from "${data.pluginPackageName}";
import service from "./${data.service}";
import securityHandlers from "./${data.security}";
const localFile = ( fileName ) => (new URL(fileName,import.meta.url)).pathname

const options = {
  specification: localFile('./${data.specFile}'),
  service,
  securityHandlers
};

export default async function (fastify, opts) {
  fastify.register(openapiGlue, options);
};
`;
